//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudManage1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eduDetail
    {
        public int sid { get; set; }
        public Nullable<int> id { get; set; }
        public string ten_percent { get; set; }
        public Nullable<int> ten_yop { get; set; }
        public string ten_inst { get; set; }
        public string twel_percent { get; set; }
        public Nullable<int> twel_yop { get; set; }
        public string twel_inst { get; set; }
        public string curr_CGPA { get; set; }
        public Nullable<int> curr_sem { get; set; }
    
        public virtual stuDetail stuDetail { get; set; }
    }
}
